#!/bin/bash

xcrun simctl spawn booted launchctl debug system/com.apple.SpringBoard --environment DYLD_INSERT_LIBRARIES=~/Projects/AppDrawer/.theos/obj/iphone_simulator/debug/Index.dylib

xcrun simctl spawn booted launchctl stop com.apple.SpringBoard
